/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTN_NHOM4;

import java.util.Calendar;
import java.util.Date;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class QUANLIMUONSACH extends javax.swing.JFrame {

    /**
     * Creates new form QLNhanVien
     */
    private int randomID = 0;
    MODELMUONSACH tableModel;
    public QUANLIMUONSACH() {
        initComponents();
        tableModel = new MODELMUONSACH(QUANLITHUVIEN.dsmuonsach.list);
        tableMuonSach.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChucNang = new javax.swing.ButtonGroup();
        labelHeader = new javax.swing.JLabel();
        labelMaThe = new javax.swing.JLabel();
        labelMaSachTruyen = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        txtMaSachTruyen = new javax.swing.JTextField();
        pnChucNang = new javax.swing.JPanel();
        ckbThem = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMuonSach = new javax.swing.JTable();
        btnThucHien = new javax.swing.JButton();
        btnTraSach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeader.setText("QUẢN LÍ MƯỢN SÁCH");

        labelMaThe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMaThe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMaThe.setText("Mã thẻ");
        labelMaThe.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelMaSachTruyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMaSachTruyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMaSachTruyen.setText("Mã sách truyện");
        labelMaSachTruyen.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtMaThe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaThe.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtMaSachTruyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaSachTruyen.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        pnChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N
        pnChucNang.setName(""); // NOI18N

        groupChucNang.add(ckbThem);
        ckbThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbThem.setSelected(true);
        ckbThem.setText("Thêm");
        ckbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tableMuonSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMuonSach);

        btnThucHien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThucHien.setText("Thực hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnTraSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTraSach.setText("Trả Sách");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(labelHeader)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTraSach)
                .addGap(50, 50, 50)
                .addComponent(btnThucHien)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelHeader)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThucHien)
                    .addComponent(btnTraSach))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbThemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        if(ckbThem.isSelected()){
            Them();
        }
        QUANLITHUVIEN.CapNhatTienThue();
        QUANLITHUVIEN.CapNhatTienChi();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_btnThucHienActionPerformed

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        try{
            if(QUANLITHUVIEN.dsmuonsach.Tim(tableMuonSach.getValueAt(tableMuonSach.getSelectedRow(), 0).toString()).isDaTra() == false){
                Date homNay = new Date();
                String Masachtruyen = tableMuonSach.getValueAt(tableMuonSach.getSelectedRow(), 2).toString();
                QUANLITHUVIEN.dsmuonsach.Tim(tableMuonSach.getValueAt(tableMuonSach.getSelectedRow(), 0).toString()).setDaTra(true);
                QUANLITHUVIEN.dsmuonsach.Tim(tableMuonSach.getValueAt(tableMuonSach.getSelectedRow(), 0).toString()).setNgayTra(homNay);
                QUANLITHUVIEN.dssachtruyen.Tim(Masachtruyen).setSoLuong(QUANLITHUVIEN.dssachtruyen.Tim(Masachtruyen).getSoLuong()+1);
                tableModel.fireTableDataChanged();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Sách này đã được trả rồi", "Lỗi", 1);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chỉ định một đối tượng trong Danh sách mượn sách", "Lỗi", 1);
        }
    }//GEN-LAST:event_btnTraSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLIMUONSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLIMUONSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLIMUONSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLIMUONSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLIMUONSACH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThucHien;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JRadioButton ckbThem;
    private javax.swing.ButtonGroup groupChucNang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelMaSachTruyen;
    private javax.swing.JLabel labelMaThe;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JTable tableMuonSach;
    private javax.swing.JTextField txtMaSachTruyen;
    private javax.swing.JTextField txtMaThe;
    // End of variables declaration//GEN-END:variables

    private void Them(){
        if(QUANLITHUVIEN.dsthethuvien.Tim(txtMaThe.getText()) != null){
            if(QUANLITHUVIEN.dssachtruyen.Tim(txtMaSachTruyen.getText()) != null){
                SACHTRUYEN sach = QUANLITHUVIEN.dssachtruyen.Tim(txtMaSachTruyen.getText());
                if(sach.getSoLuong() > 0){
                    Date homNay = new Date();
                    randomID++;
                    MUONSACH ms = new MUONSACH("MS0"+Integer.toString(randomID), txtMaThe.getText().toUpperCase(), txtMaSachTruyen.getText().toUpperCase(), homNay, null, false);
                    QUANLITHUVIEN.dsmuonsach.Them(ms);
                    sach.setSoLuong(sach.getSoLuong()-1);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Số sách trong kho đã hết", "Lỗi", 1);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Mã sách không tồn tại", "Lỗi", 1);
                txtMaSachTruyen.requestFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Mã thẻ không tồn tại", "Lỗi", 1);
            txtMaThe.requestFocus();
        }
    }
    
}
