/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTN_NHOM4;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QUANLISACHTRUYEN extends javax.swing.JFrame {
    
    MODELSACHTRUYEN tableModel;
    private int randomID = 0;
    public QUANLISACHTRUYEN() {
        initComponents();
        txtMaSachTruyen.setVisible(false);
        labelMaSachTruyen.setVisible(false);
        tableModel = new MODELSACHTRUYEN(QUANLITHUVIEN.dssachtruyen.list);
        tableSachTruyen.setModel(tableModel);
    }

/**
     * Creates new form QLNhanVien
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChucNang = new javax.swing.ButtonGroup();
        groupSachTruyen = new javax.swing.ButtonGroup();
        labelHeader = new javax.swing.JLabel();
        labelMaSachTruyen = new javax.swing.JLabel();
        labelTenSachTruyen = new javax.swing.JLabel();
        labelSoLuong = new javax.swing.JLabel();
        labelDonGiaThue = new javax.swing.JLabel();
        txtMaSachTruyen = new javax.swing.JTextField();
        txtTenSachTruyen = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGiaThue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ckbThem = new javax.swing.JRadioButton();
        ckbTimKiem = new javax.swing.JRadioButton();
        ckbXoa = new javax.swing.JRadioButton();
        ckbCapNhat = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        ckbSach = new javax.swing.JRadioButton();
        ckbTruyen = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSachTruyen = new javax.swing.JTable();
        btnThucHien = new javax.swing.JButton();
        labelChuyenNganh = new javax.swing.JLabel();
        txtChuyenNganh = new javax.swing.JTextField();
        btnDatLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeader.setText("QUẢN LÍ SÁCH TRUYỆN");

        labelMaSachTruyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMaSachTruyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMaSachTruyen.setText("Mã sách truyện");
        labelMaSachTruyen.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelTenSachTruyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTenSachTruyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTenSachTruyen.setText("Tên sách truyện");
        labelTenSachTruyen.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSoLuong.setText("Số lượng");
        labelSoLuong.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelDonGiaThue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDonGiaThue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDonGiaThue.setText("Đơn giá thuê");
        labelDonGiaThue.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtMaSachTruyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaSachTruyen.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtTenSachTruyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenSachTruyen.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtDonGiaThue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDonGiaThue.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.setName(""); // NOI18N

        groupChucNang.add(ckbThem);
        ckbThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbThem.setSelected(true);
        ckbThem.setText("Thêm");
        ckbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbThemActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbTimKiem);
        ckbTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbTimKiem.setText("Tìm Kiếm");
        ckbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTimKiemActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbXoa);
        ckbXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbXoa.setText("Xóa");
        ckbXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbXoaActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbCapNhat);
        ckbCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbCapNhat.setText("Cập Nhật");
        ckbCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ckbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ckbCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ckbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại Sách Truyện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N

        groupSachTruyen.add(ckbSach);
        ckbSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbSach.setSelected(true);
        ckbSach.setText("Sách");
        ckbSach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbSachItemStateChanged(evt);
            }
        });
        ckbSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSachActionPerformed(evt);
            }
        });

        groupSachTruyen.add(ckbTruyen);
        ckbTruyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbTruyen.setText("Truyện");
        ckbTruyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbTruyenItemStateChanged(evt);
            }
        });
        ckbTruyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTruyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ckbTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableSachTruyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableSachTruyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableSachTruyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSachTruyenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSachTruyen);

        btnThucHien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThucHien.setText("Thực hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        labelChuyenNganh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelChuyenNganh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelChuyenNganh.setText("Chuyên ngành/Thể loại");
        labelChuyenNganh.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtChuyenNganh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtChuyenNganh.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnDatLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTenSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDonGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(labelHeader)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDatLai)
                .addGap(90, 90, 90)
                .addComponent(btnThucHien)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelHeader)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTenSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSachTruyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDonGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThucHien)
                    .addComponent(btnDatLai))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ckbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbThemActionPerformed
        //txtMaSachTruyen.setEnabled(true);
        txtMaSachTruyen.setVisible(false);
        labelMaSachTruyen.setVisible(false);
        txtTenSachTruyen.setEnabled(true);
        txtSoLuong.setEnabled(true);
        txtDonGiaThue.setEnabled(true);
        txtChuyenNganh.setEnabled(true);
        
    }//GEN-LAST:event_ckbThemActionPerformed

    private void ckbXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbXoaActionPerformed
        txtMaSachTruyen.setVisible(true);
        labelMaSachTruyen.setVisible(true);
        txtMaSachTruyen.setEnabled(true);
        txtTenSachTruyen.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtDonGiaThue.setEnabled(false);
        txtChuyenNganh.setEnabled(false);
    }//GEN-LAST:event_ckbXoaActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        if(ckbThem.isSelected()){
            Them();
        }
        if(ckbXoa.isSelected()){
            Xoa();
            DatLai();
        }
        if(ckbCapNhat.isSelected()){
            CapNhat();
        }
        if(ckbTimKiem.isSelected()){
            Tim(txtMaSachTruyen.getText());
        }
        QUANLITHUVIEN.CapNhatTienThue();
        QUANLITHUVIEN.CapNhatTienChi();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_btnThucHienActionPerformed

    private void tableSachTruyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSachTruyenMouseClicked
        Tim(tableSachTruyen.getValueAt(tableSachTruyen.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tableSachTruyenMouseClicked

    private void ckbSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSachActionPerformed
        //txtChuyenNganh.setText("Chuyên ngành");
    }//GEN-LAST:event_ckbSachActionPerformed

    private void ckbTruyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTruyenActionPerformed
        //txtChuyenNganh.setText("Thể loại");
    }//GEN-LAST:event_ckbTruyenActionPerformed

    private void ckbSachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbSachItemStateChanged

    }//GEN-LAST:event_ckbSachItemStateChanged

    private void ckbTruyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbTruyenItemStateChanged

    }//GEN-LAST:event_ckbTruyenItemStateChanged

    private void ckbCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCapNhatActionPerformed
        txtMaSachTruyen.setVisible(true);
        labelMaSachTruyen.setVisible(true);
        txtMaSachTruyen.setEnabled(true);
        txtTenSachTruyen.setEnabled(true);
        txtSoLuong.setEnabled(true);
        txtDonGiaThue.setEnabled(true);
        txtChuyenNganh.setEnabled(true);
    }//GEN-LAST:event_ckbCapNhatActionPerformed

    private void ckbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTimKiemActionPerformed
        txtMaSachTruyen.setVisible(true);
        labelMaSachTruyen.setVisible(true);
        txtMaSachTruyen.setEnabled(true);
        txtTenSachTruyen.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtDonGiaThue.setEnabled(false);
        txtChuyenNganh.setEnabled(false);
    }//GEN-LAST:event_ckbTimKiemActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        DatLai();
    }//GEN-LAST:event_btnDatLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLISACHTRUYEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLISACHTRUYEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLISACHTRUYEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLISACHTRUYEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLISACHTRUYEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JRadioButton ckbCapNhat;
    private javax.swing.JRadioButton ckbSach;
    private javax.swing.JRadioButton ckbThem;
    private javax.swing.JRadioButton ckbTimKiem;
    private javax.swing.JRadioButton ckbTruyen;
    private javax.swing.JRadioButton ckbXoa;
    private javax.swing.ButtonGroup groupChucNang;
    private javax.swing.ButtonGroup groupSachTruyen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelChuyenNganh;
    private javax.swing.JLabel labelDonGiaThue;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelMaSachTruyen;
    private javax.swing.JLabel labelSoLuong;
    private javax.swing.JLabel labelTenSachTruyen;
    private javax.swing.JTable tableSachTruyen;
    private javax.swing.JTextField txtChuyenNganh;
    private javax.swing.JTextField txtDonGiaThue;
    private javax.swing.JTextField txtMaSachTruyen;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSachTruyen;
    // End of variables declaration//GEN-END:variables
    
    private void DatLai(){
        txtTenSachTruyen.setText("");
        txtDonGiaThue.setText("");
        txtSoLuong.setText("");
        txtChuyenNganh.setText("");
    }
    
    private void Them(){
        try{
            if(ckbSach.isSelected()){
                SACH s = new SACH("ST0"+Integer.toString(++randomID), txtTenSachTruyen.getText(), Double.parseDouble(txtSoLuong.getText()), Double.parseDouble(txtDonGiaThue.getText()), txtChuyenNganh.getText(), 0);
                QUANLITHUVIEN.dssachtruyen.Them(s);
            }

            if(ckbTruyen.isSelected()){
                TRUYEN t = new TRUYEN("ST0"+Integer.toString(++randomID), txtTenSachTruyen.getText(), Double.parseDouble(txtSoLuong.getText()), Double.parseDouble(txtDonGiaThue.getText()), txtChuyenNganh.getText(), 0);
                QUANLITHUVIEN.dssachtruyen.Them(t);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu nhập vào phải là Số không phải Chữ", "Lỗi", 1);
        }
    }
    
    private void Xoa(){
        QUANLITHUVIEN.dssachtruyen.Xoa(txtMaSachTruyen.getText());
    }
    
    private void CapNhat(){
        try{
            if(ckbSach.isSelected()){
                SACH s = new SACH(txtMaSachTruyen.getText(), txtTenSachTruyen.getText(), Double.parseDouble(txtSoLuong.getText()), Double.parseDouble(txtDonGiaThue.getText()), txtChuyenNganh.getText(), 0);
                QUANLITHUVIEN.dssachtruyen.CapNhat(s);
            }

            if(ckbTruyen.isSelected()){
                TRUYEN t = new TRUYEN(txtMaSachTruyen.getText(), txtTenSachTruyen.getText(), Double.parseDouble(txtSoLuong.getText()), Double.parseDouble(txtDonGiaThue.getText()), txtChuyenNganh.getText(), 0);
                QUANLITHUVIEN.dssachtruyen.CapNhat(t);
            }
                }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu nhập vào phải là Số không phải Chữ", "Lỗi", 1);
        }
    }
    
    private void Tim(String Masach){
        SACHTRUYEN st = QUANLITHUVIEN.dssachtruyen.Tim(Masach);
        txtMaSachTruyen.setText(st.getMaSachTruyen());
        txtTenSachTruyen.setText(st.getTenSachTruyen());
        txtSoLuong.setText(String.valueOf(st.getSoLuong()));
        txtDonGiaThue.setText(String.valueOf(st.getDonGiaThue()));
        if(st instanceof SACH){
            ckbSach.setSelected(true);
            txtChuyenNganh.setText(((SACH) st).getChuyenNganh());
            ckbSach.setSelected(true);
        }
        if(st instanceof TRUYEN){
            ckbTruyen.setSelected(true);
            txtChuyenNganh.setText(((TRUYEN) st).getTheLoai());
            ckbTruyen.setSelected(true);
        }
    }

}
