/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTN_NHOM4;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class QUANLITHETHUVIEN extends javax.swing.JFrame {

    /**
     * Creates new form QLNhanVien
     */
    private int randomID = 0;
    MODELTHETHUVIEN tableModel;
    public QUANLITHETHUVIEN() {
        initComponents();
        txtMaThe.setVisible(false);
        labelMaThe.setVisible(false);
        tableModel = new MODELTHETHUVIEN(QUANLITHUVIEN.dsthethuvien.list);
        tableTheThuVien.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChucNang = new javax.swing.ButtonGroup();
        labelHeader = new javax.swing.JLabel();
        labelMaThe = new javax.swing.JLabel();
        labelTenChuThe = new javax.swing.JLabel();
        labelDiaChi = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        txtTenChuThe = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        pnChucNang = new javax.swing.JPanel();
        ckbThem = new javax.swing.JRadioButton();
        ckbTimKiem = new javax.swing.JRadioButton();
        ckbXoa = new javax.swing.JRadioButton();
        ckbCapNhat = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTheThuVien = new javax.swing.JTable();
        btnThucHien = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeader.setText("QUẢN LÍ THẺ THƯ VIỆN");

        labelMaThe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMaThe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMaThe.setText("Mã thẻ");
        labelMaThe.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelTenChuThe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTenChuThe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTenChuThe.setText("Tên chủ thẻ");
        labelTenChuThe.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelDiaChi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDiaChi.setText("Địa chỉ");
        labelDiaChi.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtMaThe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaThe.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtTenChuThe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenChuThe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenChuThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenChuTheActionPerformed(evt);
            }
        });

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        pnChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N
        pnChucNang.setName(""); // NOI18N

        groupChucNang.add(ckbThem);
        ckbThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbThem.setSelected(true);
        ckbThem.setText("Thêm");
        ckbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbThemActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbTimKiem);
        ckbTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbTimKiem.setText("Tìm Kiếm");
        ckbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTimKiemActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbXoa);
        ckbXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbXoa.setText("Xóa");
        ckbXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbXoaActionPerformed(evt);
            }
        });

        groupChucNang.add(ckbCapNhat);
        ckbCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbCapNhat.setText("Cập Nhật");
        ckbCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addComponent(ckbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ckbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ckbCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ckbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tableTheThuVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableTheThuVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableTheThuVien);

        btnThucHien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThucHien.setText("Thực hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnDatLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTenChuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenChuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(labelHeader)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDatLai)
                .addGap(90, 90, 90)
                .addComponent(btnThucHien)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelHeader)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTenChuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenChuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThucHien)
                    .addComponent(btnDatLai))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbThemActionPerformed
        txtMaThe.setVisible(false);
        labelMaThe.setVisible(false);
        txtMaThe.setEnabled(true);
        txtTenChuThe.setEnabled(true);
        txtDiaChi.setEnabled(true);
    }//GEN-LAST:event_ckbThemActionPerformed

    private void ckbXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbXoaActionPerformed
        txtMaThe.setEnabled(true);
        txtTenChuThe.setEnabled(false);
        txtDiaChi.setEnabled(false);
    }//GEN-LAST:event_ckbXoaActionPerformed

    private void txtTenChuTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenChuTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenChuTheActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void ckbCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCapNhatActionPerformed
        txtMaThe.setEnabled(true);
        txtTenChuThe.setEnabled(true);
        txtDiaChi.setEnabled(true);
    }//GEN-LAST:event_ckbCapNhatActionPerformed

    private void ckbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTimKiemActionPerformed
        txtMaThe.setEnabled(true);
        txtTenChuThe.setEnabled(false);
        txtDiaChi.setEnabled(false);
    }//GEN-LAST:event_ckbTimKiemActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        if(ckbThem.isSelected()){
            Them();
        }
        if(ckbXoa.isSelected()){
            Xoa();
            DatLai();
        }
        if(ckbCapNhat.isSelected()){
            CapNhat();
        }
        if(ckbTimKiem.isSelected()){
            Tim(txtMaThe.getText());
        }
        QUANLITHUVIEN.CapNhatTienThue();
        QUANLITHUVIEN.CapNhatTienChi();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_btnThucHienActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        DatLai();
    }//GEN-LAST:event_btnDatLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLITHETHUVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLITHETHUVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLITHETHUVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLITHETHUVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLITHETHUVIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JRadioButton ckbCapNhat;
    private javax.swing.JRadioButton ckbThem;
    private javax.swing.JRadioButton ckbTimKiem;
    private javax.swing.JRadioButton ckbXoa;
    private javax.swing.ButtonGroup groupChucNang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDiaChi;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelMaThe;
    private javax.swing.JLabel labelTenChuThe;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JTable tableTheThuVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtTenChuThe;
    // End of variables declaration//GEN-END:variables

    private void DatLai(){
        txtMaThe.setText("");
        txtTenChuThe.setText("");
        txtDiaChi.setText("");
    }
    
    private void Them(){
        randomID++;
        Calendar homNay = Calendar.getInstance();
        homNay.setTime(new Date());
        homNay.add(Calendar.YEAR, 1);
        THETHUVIEN ttv = new THETHUVIEN("TTV0"+Integer.toString(randomID), txtTenChuThe.getText(),txtDiaChi.getText(), homNay.getTime());
        QUANLITHUVIEN.dsthethuvien.Them(ttv);
    }
    
    private void Xoa(){
        QUANLITHUVIEN.dssachtruyen.Xoa(txtMaThe.getText());
    }
    
    private void CapNhat(){
        THETHUVIEN ttv = new THETHUVIEN(txtMaThe.getText(), txtTenChuThe.getText(),txtDiaChi.getText());
        QUANLITHUVIEN.dsthethuvien.CapNhat(ttv);

    }
    
    private void Tim(String Mathe){
        THETHUVIEN ttv = QUANLITHUVIEN.dsthethuvien.Tim(Mathe);
        txtMaThe.setText(ttv.getMaThe());
        txtTenChuThe.setText(ttv.getTenChuThe());
        txtDiaChi.setText(ttv.getDiaChi());
        }
    }
